<?php

/**
 * @file
 * Makes TinyMCE Templates available as plugin for client-side editors integrated via
 * Wysiwyg API.
 */

/**
 * Implements hook_filter_info().
 *
 * @todo Port this to 8.x filters.
 */
function wysiwyg_template_filter_info() {
  $filters['wysiwyg_template_cleanup'] = array(
    'title' => t('Cleanup Wysiwyg Templates'),
    'description' => t('Wysiwyg templates can contain code and attributes that are important for editing but should be removed on public pages.'),
    'process callback' => '_wysiwyg_template_filter_cleanup',
  );
  return $filters;
}

/**
 * Callback to cleanup content from wysiwyg template specific code for editors.
 *
 * @param $text
 * @return string
 */
function _wysiwyg_template_filter_cleanup($text) {
  $text = str_replace(array('contenteditable="true"', 'contenteditable="false"'), '', $text);
  return $text;
}

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function wysiwyg_template_wysiwyg_plugin($editorName, $version) {
  switch ($editorName) {
    case 'tinymce':
      return array(
        'template' => array(
          'buttons' => array('template' => t('Insert templates')),
          'url' => 'http://drupal.org/project/wysiwyg_template',
          'internal' => TRUE,
          'options' => array(
            'template_external_list_url' => _wysiwyg_template_get_list_url($editorName),
            //load the javascript template list
            //'template_selected_content_classes' => variable_get('wysiwyg_template_selected_content_classes', ''),
            //'template_replace_values' => array('caption' => 'Replace with this content')
          ),
          'extended_valid_elements' => array( //tinymce specific - allows additional elements to be used
            'img[id|class|src|border=0|alt|title|width|height|align|name|style]',
          ),
          'load' => TRUE,
        ),
      );
      break;
    case 'ckeditor':
      return array(
        'templates' => array(
          'buttons' => array('Templates' => t('Insert templates')),
          'url' => 'http://drupal.org/project/wysiwyg_template',
          'internal' => TRUE,
          'options' => array(
            'templates_files' => array(_wysiwyg_template_get_list_url($editorName)),
            //load the javascript template list
            'templates_replaceContent' => false,
          ),
          'load' => FALSE,
        ),
      );
      break;
    case 'fckeditor':
      return array(
        'templates' => array(
          'buttons' => array('Templates' => t('Insert templates')),
          'url' => 'http://drupal.org/project/wysiwyg_template',
          'internal' => TRUE,
          'options' => array(
            'TemplatesXmlPath' => array(_wysiwyg_template_get_list_url($editorName)),
            //load the javascript template list
          ),
          'load' => FALSE,
        ),
      );
      break;
  }
}

function wysiwyg_template_ckeditor_settings_alter(&$settings) {
  $settings['templates_files'] = array(_wysiwyg_template_get_list_url('ckeditor'));
}

/**
 * Generate javascript for template loading
 */
function wysiwyg_template_list_js($editorName, $contentType) {
  global $base_url;
  //don't cache templates
  drupal_add_http_header('CacheControl', 'no-cache');
  drupal_add_http_header('Expires', '-1');
  drupal_add_http_header('Content-Type', 'text/javascript; charset=UTF-8');
  $templates = wysiwyg_template_load_all($contentType);
  switch ($editorName) {
    case 'tinymce':
      print 'var tinyMCETemplateList = ';
      $outArray = array();
      foreach ($templates as $template) {
        // @FIXME
// url() expects a route name or an external URI.
// $outArray[] = array(
//           $template['title'],
//           url('wysiwyg-templates/' . $editorName . '/load/') . $template['name'],
//           $template['description'],
//         );

      }
      print json_encode($outArray) . ";";
      break;
    case 'ckeditor':
      print "CKEDITOR.addTemplates( 'default', { imagesPath:'" . $base_url . "', templates: ";
      // load the templates into the json array structure
      foreach ($templates as &$template) {
        $template['html'] = $template['body'];
        unset($template['body']);
        unset($template['tid']);
      }
      print json_encode($templates);
      print "});";
      break;
    case 'fckeditor':
      print '<?xml version="1.0" encoding="utf-8" ?>';
      print '<Templates imagesBasePath="">';
      foreach ($templates as $template) {
        print '<Template title="' . \Drupal\Component\Utility\Html::escape($template['title']) . '" image="">';
        print '<Description>' . \Drupal\Component\Utility\Html::escape($template['description']) . '</Description>';
        print '<Html><![CDATA[';
        print $template['body'];
        print ']]></Html></Template>';
      }
      print '</Templates>';
      break;
    case '':
      break;
  }
}

/**
 * Menu callback to display the loaded template
 */
function wysiwyg_template_html_print($body, $editorName) {
  //don't cache templates
  drupal_add_http_header('CacheControl', 'no-cache');
  drupal_add_http_header('Expires', '-1');
  drupal_add_http_header('Content-Type', 'text/javascript; charset=UTF-8');
  switch ($editorName) {
    case 'tinymce':
      print $body;
      break;
  }
}

/**
 * Provide a list of content types for which the template $name is limited to.
 *
 * @todo Port this functionality.
 */
function wysiwyg_template_load_template_content_types($name) {
  $query = db_select('wysiwyg_templates_content_types', 'wc');
  $query->join('node_type', 'nt', 'wc.type = nt.type');
  return $query
    ->fields('wc', array('type'))
    ->fields('nt', array('name'))
    ->condition('wc.name', $name)
    ->execute()
    ->fetchAllKeyed();
}

/**
 * Implements hook_image_default_styles().
 *
 * @todo Port this functionality.
 */
function wysiwyg_template_image_default_styles() {
  $styles = array();
  // supply the default image thumbnail style
  $styles['wysiwyg_template_thumbnail'] = array(
    'effects' => array(
      array(
        'name' => 'image_resize',
        'data' => array(
          'width' => 100,
          'height' => 70,
        ),
        'weight' => 0,
      ),
    ),
  );
  return $styles;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @todo Port this functionality
 */
function wysiwyg_template_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  $type = $form['#node_type']->type;
  $form['wysiwyg_template'] = array(
    '#type' => 'fieldset',
    '#title' => t('Wysiwyg Template'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
  );
  $form['wysiwyg_template']['wysiwyg_template_default'] = array(
    '#type' => 'select',
    '#title' => t('Default template for this content type'),
    '#options' => wysiwyg_template_load_all($type, TRUE, TRUE),
    '#default_value' => wysiwyg_template_load_default($type),
  );
  $form['#submit'][] = 'wysiwyg_template_form_node_type_form_submit';
}
