<?php

use Drupal\editor\Entity\Editor;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\node\Entity\NodeType;
use Drupal\wysiwyg_template\Entity\Template;
use Drupal\wysiwyg_template\Form\SettingsForm;
use Symfony\Component\Finder\Finder;
use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_editor_js_settings_alter().
 */
function wysiwyg_template_editor_js_settings_alter(array &$settings) {
  // Change url to be bundle specific if creating or editing an entity.
  $route_match = Drupal::routeMatch();
  $entity_type = NULL;
  $bundle = NULL;

  foreach (Drupal::service('wysiwyg_template.services')->getEntityTypesAndBundles() as $entity_type => $defintion) {
    if (empty($defintion['bundles'])) {
      // No templates for this entity type.
      continue;
    }
    if ($route_match->getRouteName() === 'entity.' . $entity_type . '.edit_form') {
      $bundle = $route_match->getParameter($entity_type)->bundle();
    }
    else if ($route_match->getRouteName() === $entity_type . '.add') {
      $bundle = $route_match->getParameter($entity_type . '_type')->get('type');
    }
    if ($bundle !== NULL && isset($defintion['bundles'][$bundle])) {
      break;
    }
    $bundle = NULL;
  }

  if ($bundle !== NULL) {
    foreach ($settings['editor']['formats'] as $format => $config) {
      if (isset($config['editorSettings']['templates_files'])) {
        $url = Url::fromRoute('wysiwyg_template.list_js.type', ['entity_type' => $entity_type, 'bundle' => $bundle]);
        $settings['editor']['formats'][$format]['editorSettings']['templates_files'] = [$url->toString()];
      }
    }
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds WYSIWYG template selection as default node content.
 *
 * @see NodeTypeForm::form()
 */
function wysiwyg_template_form_node_type_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeTypeInterface $bundle */
  $bundle = $form_state->getFormObject()->getEntity();
  $templates = Template::loadByTypeAndBundle('node', $bundle->id());
  $form['wysiwyg_template'] = [
    '#type' => 'details',
    '#title' => t('WYSIWYG template'),
    '#group' => 'additional_settings',
  ];
  $form['wysiwyg_template']['wysiwyg_template_default'] = [
    '#type' => 'select',
    '#options' => array_map(static function($item) {
      return $item->label();
    }, $templates),
    '#default_value' => $bundle->getThirdPartySetting('wysiwyg_template', 'default_template'),
    '#title' => t('Default template for this content type'),
    '#empty_value' => '',
  ];

  $form['#entity_builders'][] = 'wysiwyg_template_form_node_type_form_builder';
}

/**
 * Entity builder for node type with WYSIWYG template options.
 *
 * @see wysiwyg_template_form_node_type_form_alter()
 */
function wysiwyg_template_form_node_type_form_builder($entity_type, NodeTypeInterface $type, array &$form, FormStateInterface $form_state) {
  $type->setThirdPartySetting('wysiwyg_template', 'default_template', $form_state->getValue('wysiwyg_template_default'));
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Set default content if configured to do so.
 */
function wysiwyg_template_form_node_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();
  /** @var \Drupal\node\NodeTypeInterface $type */
  $type = NodeType::load($node->getType());
  if ($node->isNew() && $template_id = $type->getThirdPartySetting('wysiwyg_template', 'default_template')) {
    /** @var \Drupal\wysiwyg_template_core\TemplateInterface $template */
    $template = Template::load($template_id);
    $form['body']['widget'][0]['#default_value'] = $template->getBody();
  }
}

/**
 * Implements hook_ckeditor_css_alter()
 */
function wysiwyg_template_ckeditor_css_alter(array &$css, Editor $editor) {
  /** @var \Drupal\Core\File\FileUrlGeneratorInterface $file_url_generator */
  $file_url_generator = \Drupal::service('file_url_generator');

  $editor_css_file = \Drupal::state()->get('wysiwyg_template.editor_css_file');

  $regenerate_css_file = FALSE;

  if (!empty($editor_css_file)) {
    $regenerate_css_file = !file_exists(SettingsForm::CSS_FILE_DIRECTORY . '/' . $editor_css_file);
  }
  else {
    $regenerate_css_file = TRUE;
  }
  if ($regenerate_css_file) {
    $editor_css_file = wysiwyg_template_regenerate_css_files('editor_css');
    \Drupal::state()->set('wysiwyg_template.editor_css_file', $editor_css_file);
  }
  $css[] = $file_url_generator->generateString(SettingsForm::CSS_FILE_DIRECTORY . '/' . $editor_css_file);
}

/**
 * Implements hook_library_info_alter()
 */
function wysiwyg_template_library_info_alter(&$libraries, $extension) {
  if ($extension == 'wysiwyg_template') {
    if (isset($libraries['view-template'])) {
      $css_uri = \Drupal::service('file_url_generator')
        ->generate(SettingsForm::getViewCSSFilePath())->toString();
      $libraries['view-template']['css']['theme'] = [
        $css_uri => array(
          'type' => 'external',
        ),
      ];
    }
  }
}

/**
 * Utility function to call for regenerating CSS files.
 */
function wysiwyg_template_regenerate_css_files($type) {
  $config = \Drupal::config('wysiwyg_template.settings');
  if ($type == 'editor_css') {
    $editor_css_file = SettingsForm::regenerateCSSFile('editor', $config->get($type));
    return \Drupal::state()->set('wysiwyg_template.editor_css_file', $editor_css_file);
  }
  else if ($type == 'view_css') {
    return \Drupal::service('file_system')->saveData($config->get($type), SettingsForm::getViewCSSFilePath(), FileSystemInterface::EXISTS_REPLACE);
  }
}


/**
 * Implements hook_cache_flush()
 */
function bwma_cache_flush() {
  $dir = \Drupal::service('file_system')->realpath('public://mce/');

  $finder = new Finder();
  $finder->name('*.css');
  $finder->files()->in($dir);

  foreach ($finder as $file) {
    $absoluteFilePath = $file->getRealPath();
    unlink($absoluteFilePath);
  }
}

/**
 * Implements hook_rebuild()
 */
function bwma_rebuild() {
  wysiwyg_template_regenerate_css_files('editor_css');
  wysiwyg_template_regenerate_css_files('view_css');
}
